### ISSUE TITLE
Can't cancel download with ctrl+c

### ISSUE THREAD

**Issue by ElegantSudo** [feross/webtorrent-cli#11]
When I hit ctrl-c in the middle of a download, it continues with the download.

**Comment by feross** [comment]
What OS and version? What version of Node.js? What version of `webtorrent-cli`?

I can't reproduce this on my machine.

**Comment by ElegantSudo** [comment]
Yup, I have to terminate the process. Latest node, Mac OS El Capitan, latest version of webtorrent-cli.

**Comment by feross** [comment]
Are you using the standard OS X Terminal app? Or a third-party app like iTerm? Are you using any streaming options like `--vlc` to stream to the VLC app?

Can you share the specific version of Node.js, El Capitan, and webtorrent-cli?

> Are you trying to hide something, or can we please properly troubleshoot this issue?

I close issues that lack sufficient details. We get so many issues where the issue reporter never comes back to provide additional detail.

**Comment by ElegantSudo** [comment]
- Node 4.4.7
- El Capitan 10.11.6
- webtorrent-cli 1.2.3

No streaming options, OS X Terminal app.

**Comment by feross** [comment]
@ElegantSudo Do you see any change in the UI when you push ctrl-c? WebTorrent captures the SIGINT signal that is sent by ctrl-c and tries to shut down the client elegantly -- disconnecting from all the peers, finishing any pending operations. Looks like it's failing to close because something is keeping the process open. Maybe a unix pipe or the `--out` command?

Can you share the exact command you're running? You don't need to share the specific magnet link, but I need to see the exact options you're using.

**Comment by ElegantSudo** [comment]
@feross I'm running `webtorrent <magnet-link-here>`. If I use ctrl-c, the terminal is cleared for a second, and then the magnet download status pops up again and it continues.

**Comment by feross** [comment]
Okay -- I'm running out of ideas here. This works perfectly fine for me, and no one else has reported this issue before. Thanks for sticking with me to get to the root of this issue.

Can you run the following commands are paste the output?

- `echo $0` (prints current shell name)
- `env` (prints shell environment variables)

- Also, are you starting webtorrent on it's own, or using some kind of dameonizer?

- Also, does this issue happen with other programs, or just webtorrent?

**Comment by ElegantSudo** [comment]
@feross don't worry about it, I'll stick with using ctrl+d.

**Comment by marcofugaro** [comment]
Hey! This happens to me as well!

I am using [bash](https://github.com/marcofugaro/dotfiles) on `Hyper 3.0.0-canary.10 (canary)` on `macOS Mojave v10.14.4`. Running `webtorrent-cli 1.12.3 (0.102.1)` on `node v11.14.0`.

The command I'm running is `webtorrent download <magnet-link-here-pasted-here>`.

Have to close the tab otherwise it wouldn't stop.

**Comment by feross** [comment]
Hey @marcofugaro, sorry this is happening for you too. Unfortunately, I can't reproduce it. I just tested with Hyper + Mojave and very similar versions to yours. It's not possible to debug this issue without additional information. If you or someone else manages to figure it out, please send a PR!

**Comment by paradoxicalNL** [comment]
For me same issue, I'm ok with using crtl-d. Just reporting. Ubuntu 22.04 / openvpn.

**Comment by thijsvandien** [comment]
Has been happening for years to me as well. Currently on macOS 14.5 with bash. Not sure what additional info to provide...?

**Comment by thijsvandien** [comment]
What I can say is that it seems that the terminal isn't actually connected to the process, in which case it is no wonder that break commands don't reach it. The shell remains active, even though WebTorrent is messing with the screen. For example, I can run `killall WebTorrent` (even though I don't get to clearly see what I'm typing) and it will exit cleanly.
