### ISSUE TITLE
DLNA Subtitles

### ISSUE THREAD

**Issue by iovis9** [feross/webtorrent-cli#18]
I'd need to add a path to the server created [here](https://github.com/feross/webtorrent/blob/master/lib/server.js) to serve the subtitles via DLNA. 

At the moment the server only admits requests to `/` and `/[number]` and obviously this would be needed in rare occasions so maybe we could add a method to add a path or something like that?

**Comment by feross** [comment]
Why does the server need to host a specific path? Can't you tell the DLNA server the URL of the subtitles file is `/[number]`?

**Comment by iovis9** [comment]
But I'd have no control over which file I'm sending to that path if the user specified a subtitles file.

**Comment by feross** [comment]
Are you saying that if the user specifies a subtitles file that is a local path on their filesystem, that there is no way to "serve" that to the remote DLNA device via HTTP?

Yeah, this is true. This is actually an issue for the chromecast and airplay devices too. The `--subtitles` command line flag takes a local filesystem path and that's why it currently only works with local video players like VLC.

To solve this, I think we can create a simple http static server to serve the user's local file. No need to add new APIs to WebTorrent. We can just start a second HTTP server. They're really lightweight in node.js.

```
var http = require('http')
var ecstatic = require('ecstatic')
 
var subtitlesServer = http.createServer(
  ecstatic({ root: pathToSubtitles })
)

// Let the OS pick a free port
subtitlesServer.listen(0, function () {
  // subtitles file is located at...
  console.log('http://' + networkAddress() + ':' + server.address().port + '/' + path.basename(pathToSubtitles))
})

// And, add this to gracefulExit()...
if (subtitlesServer) {
  subtitlesServer.close()
} 
```

**Comment by iovis9** [comment]
This was the other option I had in mind but I didn't know if you had a clean way to reuse that server instead of creating a new one. Thanks for the snippet!

**Comment by feross** [comment]
It would be possible to reach into the private properties of the torrent
object to access the server, but it's probably best to not mess around with
the server that WebTorrent is managing. The CLI just ought to use public
WebTorrent APIs IMO :)
